ingesterPort: 9044                            # Port to run the Ingestion Server on, Example: 9044

# Comment out either 'localFile' or 'url' to use only one at a time.  
pricingInfo:
  # localFile:
  #   path: "/assets/pricing.json" # Path to local JSON file with LLM Pricing data
  url: "https://raw.githubusercontent.com/dokulabs/ingester/main/assets/pricing.json" # URL to download Pricing data file

# Configuration for the Doku Backend Database (TimescaleDB)
dbConfig:
  name: "DBNAME"                              # Name of the database, Example: "postgres"
  username: "USERNAME"                        # Username to connect to the database, Example: "admin"
  password: "PASSWORD"                        # Password to connect to the database, Example: "DOKU"
  host: "HOSTURL"                             # Hostname of the database, Example: "174.21.1.2"
  port: DBPORT                                # Port of the database, Example: 5432
  sslMode: SSLMODE                            # SSL Mode of the database, Example: "require"
  maxOpenConns: MAXOPENCONNS                  # Maximum number of open connections to the database, Example: 15
  maxIdleConns: MAXOPENCONNS                  # Maximum number of idle connections to the database, Example: 15
  dataTable: DATATABLE                        # Name of the table to store LLM Data, Example: "DOKU"
  apiKeyTable: APIKEYTABLE                    # Name of the table to store API Keys, Example: "APIKEYS"

# Configure Platform to export LLM Observability Data from Doku
# Only one platform can be enabled at a time, To enable a platform, set enabled to true and fill in the required fields for that platform.
observabilityPlatform:
  enabled: false                                                 # Enable or Disable the Observability Platform, Example: true
  # grafanaCloud:
  #   promUrl: "influx-line-proxy-url"                           # URL to the Influx Line Proxy URL of the Grafana Cloud Prometheus Instance
  #   promUsername: "prometheus-userid"                          # Prometheus User ID of the Grafana Cloud Prometheus Instance
  #   lokiUrl: "loki-push-url"                                   # URL to the Loki Push URL of the Grafana Cloud Loki Instance
  #   lokiUsername: "loki-username"                              # Loki Username of the Grafana Cloud Loki Instance
  #   accessToken: "grafana-cloud-access-token"                  # Access Token of the Grafana Cloud Instance

  # newRelic:
  #   metricsUrl: "https://metric-api.newrelic.com/metric/v1"    # URL to the New Relic Metric API
  #   logsUrl: "https://log-api.newrelic.com/log/v1"             # URL to the New Relic Log API
  #   key: "newrelic-api-key"                                    # Ingest API Key of the New Relic Account