ingesterPort: 9044

# Comment out either 'localFile' or 'url' to use only one at a time.  
pricingInfo:
  localFile:
    path: "/Users/ishanjain/ingester/assets/pricing.json" # Path to local JSON file with LLM Pricing data
  #url: "https://raw.githubusercontent.com/dokulabs/ingester/main/assets/pricing.json" # URL to download Pricing data file

# Configuration for the Doku Backend Database (TimescaleDB)
dbConfig:
  name: postgres
  username: admin
  password: "DOKU"
  host: 174.138.123.61
  port: 5432
  sslMode: require
  maxOpenConns: 15
  maxIdleConns: 15
  dataTable: DOKU
  apiKeyTable: APIKEY

# Configure Platform to export LLM Observability Data from Doku
observabilityPlatform:
  enabled: true
  grafanaCloud:
    promUrl: "influx-line-proxy-url"
    promUsername: "prometheus-userid"
    lokiUrl: "loki-push-url"
    lokiUsername: "loki-username"
    accessToken: "grafana-cloud-access-token"