ingesterPort: 9044

# Comment out either 'localFile' or 'url' to use only one at a time.  
pricingInfo:
  # localFile:
  #   path: "../assets/pricing.json" # Path to local JSON file with LLM Pricing data
  url: "https://raw.githubusercontent.com/dokulabs/ingester/main/assets/pricing.json" # URL to download Pricing data file

# Configuration for the Doku Backend Database (TimescaleDB)
dbConfig:
  name: postgres
  username: admin
  password: "DOKU"
  host: 144.126.252.247
  port: 5432
  sslMode: require
  maxOpenConns: 15
  maxIdleConns: 15
  dataTable: DOKU
  apiKeyTable: APIKEY

# Configure Platform to export LLM Observability Data from Doku
observabilityPlatform:
  enabled: false
  grafanaCloud:
    logsUrl: "https://logs-prod-us-central1.grafana.net"
    logsUsername: "your_loki_username"
    cloudAccessToken: "your_grafana_cloud_api_token"